master/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'AuthController@index');
Route::get('/logout', 'AuthController@logout');
Route::post('/login', 'AuthController@login');

Route::group(['middleware' => 'privi.auth'], function () {
    Route::get('/dashboard', 'DashboardController@index');
});

master/app/Code.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Code extends Model
{
    function privi(){
        return $this->belongsTo(Privi::class, 'user_id');
    }
}

master/app/MakePage.php
<?php
/**
 * Created by PhpStorm.
 * User: Flash
 * Date: 12/12/2017
 * Time: 11:15 AM
 */

namespace App;

use App\User;
use Cartalyst\Sentry\Sentry;
use Vertopia\Portal\Core as VPC;

class MakePage
{
    static function make($view, $items = [])
    {
        $sentry = new Sentry();
        $user = $sentry->getUser();
        $user = User::findOrFail($user->getId());

        return view($view)
            ->with(array_merge([
                'user' => $user
            ], $items));
    }

    static function getUser()
    {
        $sentry = new Sentry();
        $user = $sentry->getUser();
        $user = User::findOrFail($user->getId());

        return $user;
    }

}

master/app/Privi.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Privi extends Model
{
    function getFirstNameAttribute($val)
    {
        return StringFormatter::titleText($val);
    }

    function getLastNameAttribute($val)
    {
        return StringFormatter::titleText($val);
    }


    function code()
    {
        return $this->hasOne(Code::class, 'user_id');
    }

}

master/app/StringFormatter.php
<?php
/**
 * Created by PhpStorm.
 * User: Flash
 * Date: 11/29/2017
 * Time: 12:10 PM
 */

namespace App;


use Carbon\Carbon;

class StringFormatter
{
    public static function descriptionText($string)
    {
        $string = stripslashes($string);
        $string = trim($string);

        $finds = [
            "'",
            "-"
        ];

        $fix = [
            "`",
            "_"
        ];

        return str_replace($finds, $fix, ucfirst($string));
    }

    static function uppercase($string)
    {
        $string = stripslashes($string);
        $string = trim($string);

        $finds = [
            "'",
            "-"
        ];

        $fix = [
            "`",
            "_"
        ];

        return str_replace($finds, $fix, strtoupper($string));
    }

    static function lowercase($string)
    {
        $string = stripslashes($string);
        $string = trim($string);

        $finds = [
            "'",
            "-"
        ];

        $fix = [
            "`",
            "_"
        ];

        return str_replace($finds, $fix, strtolower($string));
    }

    public static function titleText($string)
    {
        $string = stripslashes($string);
        $string = trim($string);

        $finds = [
            "'",
            "-"
        ];

        $fix = [
            "`",
            "_"
        ];

        return str_replace($finds, $fix, ucwords($string));
    }

    static function humanDate($date)
    {
        return Carbon::createFromFormat('Y-m-d H:i:s', $date)->diffForHumans();
    }
}

master/app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

master/app/Http/Controllers/AuthController.php
<?php

namespace App\Http\Controllers;

use Cartalyst\Sentry\Sentry;
use Cartalyst\Sentry\Users\LoginRequiredException;
use Cartalyst\Sentry\Users\PasswordRequiredException;
use Cartalyst\Sentry\Users\UserNotActivatedException;
use Cartalyst\Sentry\Users\UserNotFoundException;
use Cartalyst\Sentry\Users\WrongPasswordException;
use Illuminate\Http\Request;

class AuthController extends Controller
{
    function index()
    {
        $sentry = new Sentry();
        if ($sentry->check()) {
            return redirect('/dashboard');
        }
        return view('auth.login');
    }

    function login(Request $request)
    {
        $errored = true;
        try {
            $sentry = new Sentry();
            // Login credentials
            $credentials = array(
                'email' => $request->email,
                'password' => $request->password,
            );

            // Authenticate the user
            $user = $sentry->authenticate($credentials, false);
            $errored = false;
            $sentry->login($user, false);
            return redirect('/dashboard');

        } catch (LoginRequiredException $e) {
            $error = 'Login field is required.';
        } catch (PasswordRequiredException $e) {
            $error = 'Password field is required.';
        } catch (WrongPasswordException $e) {
            $error = 'Wrong password, try again.';
        } catch (UserNotFoundException $e) {
            $error = 'User was not found.';
        } catch (UserNotActivatedException $e) {
            $error = 'User is not activated.';
        }
        if ($errored) {
            return redirect()->back()
                ->withInput($request->all())
                ->withErrors([$error]);
        }
    }

    function logout()
    {
        $sentry = new Sentry();
        $sentry->logout();
        return redirect('/');
    }
}

master/app/Http/Controllers/CodeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class CodeController extends Controller
{
    //
}

master/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

master/app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\MakePage;

class DashboardController extends Controller
{
    function index(){
        return MakePage::make('index');
    }
}

master/app/Http/Controllers/PriviController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class PriviController extends Controller
{
    //
}

master/resources/views/index.blade.php
@extends('layouts.header')
@section('title')
    Dashboard
@endsection
@section('description')
    {{ $app_name }} Dashboard
@endsection
@section('content')
    this will be home
@endsection

master/resources/views/layouts/auth.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>
        @yield('title')
    </title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="{{ asset('adminLTE/bower_components/bootstrap/dist/css/bootstrap.min.css') }}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{{ asset('adminLTE/bower_components/font-awesome/css/font-awesome.min.css') }}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="{{ asset('adminLTE/bower_components/Ionicons/css/ionicons.min.css') }}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{ asset('adminLTE/dist/css/AdminLTE.min.css') }}">
    <!-- iCheck -->
    <link rel="stylesheet" href="{{ asset('adminLTE/plugins/iCheck/square/blue.css') }}">
    <link rel="stylesheet" href="{{ asset('css/parsley.css') }}">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Google Font -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
    <script src='https://www.google.com/recaptcha/api.js'></script>
</head>
<body class="hold-transition login-page">
<div class="login-box">
    <div class="login-logo">
        <a href="adminLTE/index2.html"><b>
                {{ $app_name }}
            </b></a>
    </div>
    <!-- /.login-logo -->
    @yield('content')
    <!-- /.login-box-body -->
</div>
<!-- /.login-box -->

<!-- jQuery 3 -->
<script src="{{ asset('adminLTE/bower_components/jquery/dist/jquery.min.js') }}"></script>
<!-- Bootstrap 3.3.7 -->
<script src="{{ asset('adminLTE/bower_components/bootstrap/dist/js/bootstrap.min.js') }}"></script>
<!-- iCheck -->
<script src="{{ asset('adminLTE/plugins/iCheck/icheck.min.js') }}"></script>
<script src="{{ asset('js/parsley.min.js') }}"></script>
<script src="{{ asset('js/auth.js') }}"></script>
<script>
    $(function () {
        $('input').iCheck({
            checkboxClass: 'icheckbox_square-blue',
            radioClass: 'iradio_square-blue',
            increaseArea: '20%' // optional
        });
    });
</script>
</body>
</html>

master/resources/views/layouts/footer.blade.php
<footer class="main-footer">
    <div class="pull-right hidden-xs">
        <b>Version</b> 1.0.1
    </div>
    <strong>Copyright &copy; {{ date('Y') }} <a href="#">
    {{ $app_name }}    
    </a>.</strong> All rights
    reserved.
</footer>

master/resources/views/layouts/header.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>
        @yield('title')
    </title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="{{ asset('adminLTE/bower_components/bootstrap/dist/css/bootstrap.min.css') }}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{{ asset('adminLTE/bower_components/font-awesome/css/font-awesome.min.css') }}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="{{ asset('adminLTE/bower_components/Ionicons/css/ionicons.min.css') }}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{ asset('adminLTE/dist/css/AdminLTE.min.css') }}">
    <link rel="stylesheet" href="{{ asset('css/abiri.css') }}">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="{{ asset('adminLTE/dist/css/skins/_all-skins.min.css') }}">
    @yield('styles')

<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Google Font -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

@include('layouts.top')
<!-- Left side column. contains the logo and sidebar -->
@include('layouts.menu')

<!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                @yield('title')
                <small>
                    @yield('description')
                </small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                <li><a href="#">
                        @yield('title')
                    </a>
                </li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            @yield('content')
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
    @include('layouts.footer')

</div>
<!-- ./wrapper -->

<!-- jQuery 3 -->
<script src="{{ asset('adminLTE/bower_components/jquery/dist/jquery.min.js') }}"></script>
<!-- Bootstrap 3.3.7 -->
<script src="{{ asset('adminLTE/bower_components/bootstrap/dist/js/bootstrap.min.js') }}"></script>
<!-- Slimscroll -->
<script src="{{ asset('adminLTE/bower_components/jquery-slimscroll/jquery.slimscroll.min.js') }}"></script>
<!-- FastClick -->
<script src="{{ asset('adminLTE/bower_components/fastclick/lib/fastclick.js') }}"></script>
<!-- AdminLTE App -->
<script src="{{ asset('adminLTE/dist/js/adminlte.min.js') }}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{{ asset('adminLTE/dist/js/demo.js') }}"></script>
@yield('scripts')
</body>
</html>

master/resources/views/layouts/menu.blade.php
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="{{ asset('img/abiri.jpeg') }}" class="img-circle" alt="User Image">
            </div>
            <div class="pull-left info">
                <p>{{ $user->first_name }} {{ $user->last_name }}</p>
                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>
        <!-- search form -->
        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search...">
                <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                </button>
              </span>
            </div>
        </form>
        <!-- /.search form -->
        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu" data-widget="tree">
            <li class="header">MAIN NAVIGATION</li>
            <li>
                <a href="/dashboard">
                    <i class="fa fa-dashboard"></i> <span>Dashboard</span>
                </a>
            </li>
            <li>
                <a href="/users">
                    <i class="fa fa-group"></i> <span>Users</span>
                </a>
            </li>
            <li>
                <a href="/cars">
                    <i class="fa fa-car"></i> <span>Cars</span>
                </a>
            </li>
            <li>
                <a href="/journeys">
                    <i class="fa fa-road"></i> <span>Journeys</span>
                </a>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-map-signs"></i> <span>Main Roads</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="/mainroads"><i class="fa fa-circle-o"></i> View Roads</a></li>
                    <li><a href="/addroads"><i class="fa fa-circle-o"></i> Add Roads</a></li>
                </ul>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-money"></i> <span>Tollgates</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="/tollgates"><i class="fa fa-circle-o"></i> View Tollgates</a></li>
                    <li><a href="/addtollgate"><i class="fa fa-circle-o"></i> Add Tollgate</a></li>
                </ul>
            </li>
            {{--            <li class="treeview">
                            <a href="#">
                                <i class="fa fa-dollar"></i> <span>E-tolls</span>
                                <span class="pull-right-container">
                                    <i class="fa fa-angle-left pull-right"></i>
                                </span>
                            </a>
                            <ul class="treeview-menu">
                                <li><a href="/etolls"><i class="fa fa-circle-o"></i> View E-tolls</a></li>
                                <li><a href="/addetoll"><i class="fa fa-circle-o"></i> Add E-toll</a></li>
                            </ul>
                        </li>--}}
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-map"></i> <span>Taxi Ranks</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="/taxiranks"><i class="fa fa-circle-o"></i> View Ranks</a></li>
                    <li><a href="/addrank"><i class="fa fa-circle-o"></i> Add Rank</a></li>
                </ul>
            </li>

            <li class="treeview">
                <a href="#">
                    <i class="fa fa-tint"></i> <span>Fuel Consumption</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="/fuels"><i class="fa fa-circle-o"></i> View Consumptions</a></li>
                    <li><a href="/addfuel"><i class="fa fa-circle-o"></i> Add Consumption</a></li>
                    <li><a href="/costs"><i class="fa fa-circle-o"></i> View Prices</a></li>
                    <li><a href="/addcost"><i class="fa fa-circle-o"></i> Add Price</a></li>
                </ul>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-check-circle-o"></i> <span>Feedback</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="/feedback"><i class="fa fa-circle-o"></i> New Feedback</a></li>
                    <li><a href="/readfeedback"><i class="fa fa-circle-o"></i> Read Feedback</a></li>
                </ul>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-times-circle-o"></i> <span>Reports</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="/reports"><i class="fa fa-circle-o"></i> New Reports</a></li>
                    <li><a href="/readreports"><i class="fa fa-circle-o"></i> Read Reports</a></li>
                </ul>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-question-circle-o"></i> <span>FAQs</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="/faqs"><i class="fa fa-circle-o"></i> View FAQs</a></li>
                    <li><a href="/addfaq"><i class="fa fa-circle-o"></i> Add FAQ</a></li>
                </ul>
            </li>

            <li class="treeview">
                <a href="#">
                    <i class="fa fa-question-circle"></i> <span>Queries</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="/newqueries"><i class="fa fa-circle-o"></i> New Queries</a></li>
                    <li><a href="/readqueries"><i class="fa fa-circle-o"></i> Read Queries</a></li>
                </ul>
            </li>

            <li>
                <a href="/subscriptions">
                    <i class="fa fa-inbox"></i> <span>Subscriptions</span>
                </a>
            </li>       <li>
                <a href="/logout">
                    <i class="fa fa-lock"></i> <span>Logout</span>
                </a>
            </li>
        </ul>
    </section>
    <!-- /.sidebar -->
</aside>s</a>

master/resources/views/layouts/top.blade.php
<header class="main-header">
    <!-- Logo -->
    <a href="/dashboard" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini"><b>A</b>LT</span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg"><b>{{ $app_name }}</b></span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </a>

        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">

                <!-- User Account: style can be found in dropdown.less -->
                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <img src="{{ asset('img/abiri.jpeg') }}" class="user-image" alt="User Image">
                        <span class="hidden-xs">{{ $user->first_name }} {{ $user->last_name }}</span>
                    </a>
                    <ul class="dropdown-menu">
                        <!-- User image -->
                        <li class="user-header">
                            <img src="{{ asset('img/abiri.jpeg') }}" class="img-circle" alt="User Image">

                            <p>
                                {{ $user->first_name }} {{ $user->last_name }}
                            </p>
                        </li>

                        <!-- Menu Footer-->
                        <li class="user-footer">
                            <div class="pull-left">
                                <a href="#" class="btn btn-default btn-flat">Profile</a>
                            </div>
                            <div class="pull-right">
                                <a href="/logout" class="btn btn-default btn-flat">Sign out</a>
                            </div>
                        </li>
                    </ul>
                </li>
                <!-- Control Sidebar Toggle Button -->
                <li>
                    <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
                </li>
            </ul>
        </div>
    </nav>
</header>